language: ruby
rvm:
  - 2.0.0
services:
  - redis-server
script: "bundle exec rake spec"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfreeimage-dev
before_script:
  - mysql -e 'create database sp_test;'
  - cp config/travis/database.yml config/database.yml
  - cp config/travis/config.yml config/config.yml
  - cp config/travis/amazon_s3.yml config/amazon_s3.yml
  - cp config/travis/facebook.yml config/facebook.yml
  - bundle exec rake db:schema:load RAILS_ENV=test
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
