source 'http://rubygems.org'
# source 'http://gems.rubyonrails.org'

gem 'rails', '~> 4.0.0'

gem 'mysql2'#, '~> 0.2.7'

# Needed for the new asset pipeline
gem 'sass-rails'#,   '~> 3.2.3'
gem 'coffee-rails'#, '~> 3.2.1'
gem 'uglifier'#, '~> 1.3.0'
gem 'jquery-ui-rails'#, '~> 4.0.1'
gem 'therubyracer'

# jQuery is the default JavaScript library in Rails 3.1
gem 'jquery-rails'

gem 'activemerchant', '~> 1.28.0'
gem 'acts_as_versioned', git: 'https://github.com/technoweenie/acts_as_versioned.git'
gem 'airbrake', '~> 3.1.5'
gem 'aws-sdk'
gem 'carmen', '~> 0.2.12'
gem 'dalli', '~> 2.2.1'
gem 'dynamic_form', '~> 1.1.4'
gem 'excelsior', '~> 0.1.0'
gem 'google-geocode', '~> 1.2.1', :require => 'google_geocode'
gem 'libv8', '~> 3.11.8'
gem 'liquid', '~> 2.4.1'
gem 'newrelic_rpm', '>= 3.5.3.25'
gem 'omniauth', '~> 1.1.1'
gem 'omniauth-cas', '~> 1.0.2'
gem 'omniauth-facebook', '~> 1.6.0'
gem 'paperclip', '~> 3.5.1'
gem 'rack-contrib', '~> 1.1.0' # 100ms
gem 'rb-fsevent', '~> 0.9'
gem 'retryable-rb', '~> 1.1.0'
gem 'siebel_donations', '~> 1.0.4'
gem 'spreadsheet', '~> 0.7.4'
gem 'tinymce-rails', '~> 4.0.6'
gem 'whenever', '~> 0.7.3'
gem 'will_paginate', '~> 3.0.0'
gem 'gcx_api', git: 'git://github.com/CruGlobal/gcx_api.git'
gem 'relay_api_client', git: 'git://github.com/CruGlobal/relay_api_client.git'
gem 'cru_lib', git: 'https://github.com/CruGlobal/cru_lib'
# gem 'cru_lib', path: '/Users/josh/htdocs/cru_lib'
gem 'image_science', '~> 1.2.5'
gem 'qe', git: 'https://github.com/CruGlobal/qe', ref: '0a8c8f9'
gem 'sidekiq-pro'
gem 'sidekiq-failures'
gem 'sidekiq-unique-jobs'
gem 'geocoder'
gem 'versionist'
gem 'active_model_serializers'
gem 'rubycas-client'
gem 'aasm'
gem 'auto_strip_attributes'

group :development, :test do
  gem 'rspec', '~> 3.0'
  gem 'quiet_assets'
  gem 'awesome_print'
  gem 'mailcatcher'
  gem 'guard-rspec'
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'unicorn'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'fuubar'
  gem 'simplecov', :require => false
  gem 'database_cleaner'
  gem 'spork-rails'#, '~> 3.2.0'
  gem 'guard-spork'
end


