# NOTE, the 'session_secret' needs to be 30 chars or longer
development:
  session_secret: ENV['session_secret']
  siebel_token: siebel_token

test:
  session_secret: ENV['session_secret']
  siebel_token: siebel_token

production:
  session_secret: ENV['session_secret']
  siebel_token: siebel_token
