# Here you can specify default options for TinyMCE across all controllers
#
default:
  theme_advanced_buttons1: "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
  theme_advanced_buttons2: ""
  theme_advanced_buttons3: ""
  theme_advanced_toolbar_location: "top"
  theme_advanced_toolbar_align: "left"